# Generated by Django 6.0.1 on 2026-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
